services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    #networks: - backend
    
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    depends_on:
      - backend
    #networks:
     # - backend

#networks:
#  backend:
#    driver: bridge

#    ports:
#      - 1234:1234
